parameters:
    app_locales: [en, cs]

twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        locales: '%app_locales%'

when@test:
    twig:
        strict_variables: true
